"""add unique workout position constraint

Revision ID: b26361557b58
Revises: f6e51a9e0f8c
Create Date: 2026-07-14 14:44:26.214894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26361557b58'
down_revision = 'f6e51a9e0f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_workout_position', ['workout_id', 'position'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint('unique_workout_position', type_='unique')

    # ### end Alembic commands ###
