"""Remove workout day unique constraint

Revision ID: c0ad481774b7
Revises: 61aa63d0dc22
Create Date: 2026-07-14 10:47:39.759660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ad481774b7'
down_revision = '61aa63d0dc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_workout_day'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_days', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_workout_day'), ['workout_id', 'day_of_week'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
